apiVersion: apps/v1
kind: Deployment
metadata:
  name: newname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newname
  template:
    metadata:
      labels:
        app: newname
    spec:
      containers:
      - image: okteto.dev/newname:latest
        name:newname
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mify.bdr.hgu"
        - name: Vless_UUID
          value: "de4eb009-4067-4e67-9d3e-477a94892d25"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "de4eb009-4067-4e67-9d3e-477a94892d25"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
